import { AiFillStar } from "react-icons/ai";

const data = [{
  img:"https://www.infotechsnepal.com/wp-content/uploads/2023/03/dell-celeron.jpg",
  title: "Dell 5470",
  price:"NPR 37,500.00",
  company:"DELL",
  processor:"Intel UHD",
  displaySize:"14″ FHD",
  star:<AiFillStar className="ratings-start"/> ,
  ram:"8GB RAM",
  storage:"256GB SSD",
  reviews:"(123 reviews)",
  color: "Black",
},
{
  img:" https://www.infotechsnepal.com/wp-content/uploads/2023/05/hp-envy-x360-i5-2-in-1-laptops-nepal.jpg",
  title: " HP Envy x360 14 ",
  price:"NPR 106,500.00 ",
  company:"HP ",
  processor:"Intel® Core™ i5-1335U ",
  displaySize:"14″ FHD ",
  star:<AiFillStar className="ratings-start"/> ,
  ram:" 8GB RAM ",
  storage:" 512GB SSD",
  reviews:"(123 reviews) ",
  color: "Silver",
},
{
  img:"https://www.infotechsnepal.com/wp-content/uploads/2023/05/Acer-Aspire-A5-15-i5-iris-xe-8gb-ram-512gb-ssd-price-nepal.jpg ",
  title: "Acer Aspire 5 ",
  price:"NPR 76,500.00 ",
  company:"Acer",
  processor:"Core i5-1335U",
  displaySize:"15.6” FHD ",
  star:<AiFillStar className="ratings-start"/>  ,
  ram:" 8GB RAM ",
  storage:"512GB SSD",
  reviews:"(123 reviews) ",
  color:"Steel Gray",
},
{
  img:"https://www.infotechsnepal.com/wp-content/uploads/2023/05/HP-VICTUS-15-FA1033NIA-core-i5-13420H-RTX%E2%84%A2-2050-8GB-RAM-512GB-SSD-15.6-FHD-1.jpg ",
  title: "HP VICTUS 15 FA1033NIA ",
  price:"NPR 116,000.00 ",
  company:"HP ",
  processor:" | Intel Core i5 13420H",
  displaySize:" 15.6″ FHD",
  star:<AiFillStar className="ratings-start"/> ,
  ram:"|8GB RAM ",
  storage:"512GB SSD ",
  reviews:"(123 reviews) ",
  color: "Blue",
},
{
  img:"https://www.infotechsnepal.com/wp-content/uploads/2023/05/lenovo-ideapad-1-ryzen-5-price-nepal.jpg ",
  title: "Lenovo IdeaPad 1  ",
  price:"NPR 62,999.00 ",
  company:"Lenovo ",
  processor:"Ryzen 5 7520U",
  displaySize:"15.6” FHD",
  star:<AiFillStar className="ratings-start"/> ,
  ram:"8GB RAM ",
  storage:"256GB SSD",
  reviews:"(123 reviews) ",
  color: "Silver ",
},
{
  img:" https://www.infotechsnepal.com/wp-content/uploads/2022/09/HP-Pavilion-X360-Core-i5-1235U.jpg",
  title: "HP Pavilion X360  ",
  price:"NPR 96,500.00",
  company:"HP ",
  processor:"Core i5-1235U",
  displaySize:"14” Touch FHD",
  star:<AiFillStar className="ratings-start"/> ,
  ram:"8GB RAM ",
  storage:" 512GB SSD",
  reviews:"(123 reviews) ",
  color: " SILVER ",
},
{
  img:"https://www.infotechsnepal.com/wp-content/uploads/2023/01/Lenovo-Ideapad-1i-price-nepal.jpg",
  title: " Lenovo IdeaPad 1i",
  price:"NPR 52,500.00",
  company:" Lenovo",
  processor:"Intel Core i3-1215U",
  displaySize:"14″ HD ",
  star:<AiFillStar className="ratings-start"/> ,
  ram:"8GB RAM ",
  storage:"256GB SSD",
  reviews:"(123 reviews) ",
  color: "Cloud Grey ",
},
{
  img:"https://www.infotechsnepal.com/wp-content/uploads/2023/03/hp-15s-fq5297nia-core%E2%84%A2-i7-1255u-iris-xe-8gb-ram-512gb-ssd-15.6-inch-3.jpg ",
  title: "HP 15s FQ5297NIA ",
  price:"NPR 97,000.00 ",
  company:"HP ",
  processor:" Core™ i7-1255U",
  displaySize:" 15.6” FHD ",
  star:<AiFillStar className="ratings-start"/> ,
  ram:"8GB RAM ",
  storage:"512GB SSD",
  reviews:"(123 reviews) ",
  color: "Light Blue and silver ",
},
{
  img:"https://www.infotechsnepal.com/wp-content/uploads/2023/07/Design-sem-nome.jpg",
  title: " HP Envy 14 X360",
  price:" NPR 150,500.00",
  company:"HP ",
  processor:"13th Gen i7",
  displaySize:"14″ FHD Display ",
  star:<AiFillStar className="ratings-start"/> ,
  ram:"16GB RAM ",
  storage:"512GB SSD ",
  reviews:"(123 reviews) ",
  color: " Silver",
},
{
  img:"https://www.infotechsnepal.com/wp-content/uploads/2023/04/Lenovo-IdeaPad-3-Ryzen-3-8GB-RAM-Price-Nepal.jpg",
  title: " Lenovo IdeaPad 3",
  price:"NPR 50,500.00",
  company:"Lenovo ",
  processor:"AMD Ryzen 3 5425U",
  displaySize:"15.6″ FHD ",
  star:<AiFillStar className="ratings-start"/> ,
  ram:"8GB RAM ",
  storage:"256GB SSD",
  reviews:"(123 reviews) ",
  color: "Silver ",
},
{
  img:"https://www.infotechsnepal.com/wp-content/uploads/2023/07/Design-sem-nome-4.jpg",
  title: "Lenovo IdeaPad Slim 3i  ",
  price:"NPR 80,500.00 ",
  company:"Lenovo ",
  processor:"i5 13th Gen ",
  displaySize:"15.6″ FHD ",
  star: <AiFillStar className="ratings-start"/> ,
  ram:"8GB RAM ",
  storage:"512GB SSD",
  reviews:"(123 reviews) ",
  color: "Silver ",
},
{
  img:"https://www.infotechsnepal.com/wp-content/uploads/2023/09/lenovo.jpg",
  title: " Lenovo Ideapad 1",
  price:"NPR 31,999.00 ",
  company:"Lenovo",
  processor:"Celeron N4020 ",
  displaySize:"15.6 Inch",
  star:<AiFillStar className="ratings-start"/> ,
  ram:" 4GB RAM ",
  storage:"256GB SSD ",
  reviews:"(123 reviews)",
  color: "Blue",
},
{
  img:"https://www.infotechsnepal.com/wp-content/uploads/2023/09/lenovov15-IGL.jpg",
  title: "Lenovo V15-IGL ",
  price:"NPR 32,999.00 ",
  company:"Lenovo",
  processor:"Intel Celeron N4020 ",
  displaySize:"15.6 Inch HD",
  star:<AiFillStar className="ratings-start"/> ,
  ram:"4GB RAM  ",
  storage:"256GB SSD",
  reviews:"(123 reviews) ",
  color: "Gray",
},
{
  img:"https://www.infotechsnepal.com/wp-content/uploads/2023/09/ASUS-go.jpg",
  title: "Asus Vivobook Go 14 E410",
  price:"NPR 35,500.00 ",
  company:"Asus",
  processor:"Intel Celeron Processor N4020 ",
  displaySize:"14.0 inch FHD  ",
  star:<AiFillStar className="ratings-start"/> ,
  ram:"4GB RAM  ",
  storage:"256GB SSD",
  reviews:"(123 reviews) ",
  color: " Rose Gold",
},
{
  img:"https://www.infotechsnepal.com/wp-content/uploads/2023/08/lenovo-2.jpg",
  title: "Lenovo Ideapad 1 ",
  price:"NPR 35,500.00",
  company:"Lenovo",
  processor:"Celeron N4020 ",
  displaySize:"15.6 Inch",
  star:<AiFillStar className="ratings-start"/> ,
  ram:"8GB RAM  ",
  storage:"256GB SSD",
  reviews:"(123 reviews) ",
  color: "Blue",
},
{
  img:"https://www.infotechsnepal.com/wp-content/uploads/2022/02/HP-14-1022wm-.jpg",
  title: "HP 14 DK1032 ",
  price:"NPR 47,500.00",
  company:"HP",
  processor:"AMD Ryzen 3 ",
  displaySize:" 14″ Display",
  star:<AiFillStar className="ratings-start"/> ,
  ram:"8GB RAM ",
  storage:"128GB SSD",
  reviews:"(123 reviews) ",
  color: "Silver",
},
{
  img:"https://www.infotechsnepal.com/wp-content/uploads/2023/07/hp-1-1.jpg",
  title: "HP 15S",
  price:"NPR 48,000.00 ",
  company:"HP",
  processor:"Ryzen 3-7320U ",
  displaySize:" 15.6″ ",
  star:<AiFillStar className="ratings-start"/> ,
  ram:"4GB RAM  ",
  storage:"256GB SSD",
  reviews:"(123 reviews) ",
  color: "White+Silver",
},
{
  img:"https://www.infotechsnepal.com/wp-content/uploads/2023/06/Untitled-design.jpg",
  title: "Acer Aspire 7 ",
  price:"NPR 83,000.00 ",
  company:"Acer",
  processor:"Ryzen 5 5500U ",
  displaySize:" 15.6″ FHD Display ",
  star:<AiFillStar className="ratings-start"/> ,
  ram:"16GB RAM  ",
  storage:"512GB SSD ",
  reviews:"(123 reviews) ",
  color: "Black",
},
{
  img:"https://www.infotechsnepal.com/wp-content/uploads/2023/09/Acer-Aspire-7-Gaming-Laptop-Core-i5-12450H-GeForce-RTX-2050-16GB-RAM-512GB-SSD-15.6-IPS-Display.jpg",
  title: "Acer Aspire 7 Laptop ",
  price:"NPR 90,000.00",
  company:"Acer",
  processor:"Core i5 12450H",
  displaySize:"15.6″ IPS Display ",
  star:<AiFillStar className="ratings-start"/> ,
  ram:"16GB RAM  ",
  storage:"256GB SSD ",
  reviews:"(123 reviews) ",
  color: " Gray",
},
{
  img:"https://www.infotechsnepal.com/wp-content/uploads/2023/03/HP-Victus-15.jpg",
  title: "HP Victus 15 ",
  price:"NPR 102,500.00",
  company:"HP",
  processor:"Core i5-12450H",
  displaySize:" 15.6-inch FHD",
  star:<AiFillStar className="ratings-start"/> ,
  ram:"8GB RAM  ",
  storage:"512GB SSD ",
  reviews:"(123 reviews) ",
  color: "Light Gray",
},
]


export default data;